# credit-service/credit-service.yml
server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb://host.docker.internal:27017/banking_credits
      auto-index-creation: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: credit-service-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      creditService:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
  timelimiter:
    instances:
      creditService:
        timeout-duration: 2s

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.nttd.banking.credit: DEBUG