# report-service/report-service.yml
server:
  port: 8088

spring:
  data:
    mongodb:
      uri: mongodb://host.docker.internal:27017/banking_reports
      auto-index-creation: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: report-service-group
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

resilience4j:
  timelimiter:
    instances:
      reportService:
        timeout-duration: 5s

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.nttd.banking.report: DEBUG